### ISSUE TITLE
Add CI using Travis

### ISSUE THREAD

**Issue by dortegau** [idealista/nginx_role#6]
We should add CI to this role using the stack below:

- Ansible
- Vagrant
- Molecule

We should configure Travis to run the unit tests in each push/merge: http://molecule.readthedocs.io/en/stable-1.18/usage.html

**Comment by jnogol** [comment]
Tried again, inspired by @jdvr 's Redis Role (https://github.com/idealista/redis-role) and found out that the problem is that `/tmp` inside the Docker container is not a good place to build sources.

Also, I would suggest to eliminate the `nginx-old` role and use the regular one but with other parameters.
